import { Knex } from 'knex';
import { ETableNames } from '../ETableNames';

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    '* as count'
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = cidadesDaBahia.map((nomeDaCidade) => ({
    nome: nomeDaCidade,
  }));
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidadesDaBahia = [
  'Abaíra',
  'Abaré',
  'Acajutiba',
  'Adustina',
  'Água Fria',
  'Aiquara',
  'Alagoinhas',
  'Alcobaça',
  'Almadina',
  'Amargosa',
  'Amélia Rodrigues',
  'América Dourada',
  'Anagé',
  'Andaraí',
  'Andorinha',
  'Angical',
  'Anguera',
  'Antas',
  'Antônio Cardoso',
  'Antônio Gonçalves',
  'Aporá',
  'Apuarema',
  'Araças',
  'Aracatu',
  'Araci',
  'Aramari',
  'Arataca',
  'Aratuípe',
  'Aurelino Leal',
  'Baianópolis',
  'Baixa Grande',
  'Banzaê',
  'Barra',
  'Barra da Estiva',
  'Barra do Choça',
  'Barra do Mendes',
  'Barra do Rocha',
  'Barreiras',
  'Barro Alto',
  'Barrocas',
  'Barro Preto',
  'Belmonte',
  'Belo Campo',
  'Biritinga',
  'Boa Nova',
  'Boa Vista do Tupim',
  'Bom Jesus da Lapa',
  'Bom Jesus da Serra',
  'Boninal',
  'Bonito',
  'Boquira',
  'Botuporã',
  'Brejões',
  'Brejolândia',
  'Brotas de Macaúbas',
  'Brumado',
  'Buerarema',
  'Buritirama',
  'Caatiba',
  'Cabaceiras do Paraguaçu',
  'Cachoeira',
  'Caculé',
  'Caém',
  'Caetanos',
  'Caetité',
  'Cafarnaum',
  'Cairu',
  'Caldeirão Grande',
  'Camacan',
  'Camaçari',
  'Camamu',
  'Campo Alegre de Lourdes',
  'Campo Formoso',
  'Canápolis',
  'Canarana',
  'Canavieiras',
  'Candeal',
  'Candeias',
  'Candiba',
  'Cândido Sales',
  'Cansanção',
  'Canudos',
  'Capela do Alto Alegre',
  'Capim Grosso',
  'Caraíbas',
  'Caravelas',
  'Cardeal da Silva',
  'Carinhanha',
  'Casa Nova',
  'Castro Alves',
  'Catolândia',
  'Catu',
  'Caturama',
  'Central',
  'Chorrochó',
  'Cícero Dantas',
  'Cipó',
  'Coaraci',
  'Cocos',
  'Conceição da Feira',
  'Conceição do Almeida',
  'Conceição do Coité',
  'Conceição do Jacuípe',
  'Conde',
  'Condeúba',
  'Contendas do Sincorá',
  'Coração de Maria',
  'Cordeiros',
  'Coribe',
  'Coronel João Sá',
  'Correntina',
  'Cotegipe',
  'Cravolândia',
  'Crisópolis',
  'Cristópolis',
  'Cruz das Almas',
  'Curaçá',
  'Dário Meira',
];
